Hooks:Add("LocalizationManagerPostInit", "ContinentalCoinsReborn", function(self)
	self:add_localized_strings({
		["menu_es_coins_progress"] = "Continental Coins",
		["bm_menu_btn_buy_mod"] = "Purchase with Continental Coins",
		["dialog_bm_purchase_coins"] = "It will cost you $money Continental Coins.",
		["menu_es_safehouse_reward_coins"] = "$amount Continental Coins.",
		["menu_challenge_safehouse_daily_reward"] = "Continental Coins to purchase safe house upgrades and weapon mods.",
		["menu_cs_reroll_text"] = "Do you want to reroll your currently available missions?$NL;$NL;This will cost you $cost; Continental Coins.",
		["menu_data_crew_item_unlock_cost"] = "Costs $cost; continental coins to unlock",
		["menu_es_safehouse_total_coins"] = "You have $amount; Continental Coins in total.",
		["menu_cs_coins"] = "Continental Coins",
		["menu_aru_job_2_reward"] = "A new weapon, Continental Coins, and the 'A War Well Fought' trophy in the safehouse.",
		["menu_cs_cant_afford"] = "You don't have enough Continental Coins for this upgrade.",
		["menu_es_safehouse_earned"] = "You earned $amount; Continental Coins on this job.",
		["dialog_crew_ability_unlock_text"] = "Costs $cost; Continental coins to unlock.",
		["menu_cs_overview_desc"] = "This is your Safe House. It starts out a bit rough, but you can upgrade it if you have enough Continental Coins. It's also the place where you display the various trophies that you collect during your criminal exploits.$NL;$NL;You earn Continental Coins by doing heists, or by doing daily jobs for the various heisters.",
		["menu_es_safehouse_max_coins"] = "You have earned the maximum amount of Continental Coins at this time.",
		["menu_aru_job_3_reward"] = "A new weapon, Continental Coins, and the 'Speed Talker' trophy in the safehouse.",
		["dialog_crew_boost_unlock_text"] = "Costs $cost; Continental coins to unlock.",
		["menu_cs_daily_desc"] = "Every day a heister in the safe house will have a challenge for you! Meet with them in the safe house to accept their challenge, and then go out into the world to complete the requirements. Complete the challenge, and they'll give you a few Continental Coins for your troubles.$NL;$NL;Wick managed to get the Payday crew membership to The Continental, so they're giving you coins for every heist you pull off. With enough coins, Charlie and his boys will come in and do a little redecorating for us, and make sure that any work done stays off the books.",
		["dialog_bm_purchase_mod_cant_afford"] = "You do not have enough Continental Coins to purchase $name;.$NL;$NL;You need $money; Continental Coins.",
		["menu_cs_upgrade_cost"] = "It will cost ##$cost;## Continental Coins to upgrade this room.",
		["dialog_upgrade_safehouse"] = "Do you really want to upgrade $character;'s room?$NL;$NL;It will cost you $cost; Continental Coins.",
		["menu_aru_job_4_reward"] = "Continental Coins, and the 'Hero's Companion' trophy in the safehouse.",
		["menu_aru_job_1_reward"] = "A new weapon, Continental Coins, and a the 'Friends in Close-Quarters' trophy in the safehouse.",
		["menu_cs_reroll_text_cant_afford"] = "You can not reroll your available missions, you need $cost; Continental Coins to do this.",
		["menu_sm_default_reward"] = "3 continental coins",
		["menu_sm_moving_up_reward"] = "6 continental coins",
		["victory_stage_cash_summary_name_safehouse"] = "Continental Coins income: ##$gained;##",
		["victory_stage_safehouse_summary"] = "You earned $amount; Continental Coins on this job.",
		["menu_challenge_trophy_reward"] = "Continental Coins and a Safe House Trophy",
		["dialog_are_you_sure_you_want_stop_cs_refund"] = "Are you sure you want to stop your Crime Spree?$NL;$NL;This will end your current spree, and no rewards will be given to you. Your initial investment of $coins; Continental Coins will be returned to you.",
		["bm_cs_continental_coin_cost"] = "$cost; Continental Coins",
		["dialog_cant_continue_cs_text"] = "You can not continue your Crime Spree as you do not have enough Continental Coins. In order to continue from $level;$BTN_SPREE_TICKET; you need $cost; Continental Coins.",
		["dialog_continue_cs_text"] = "Do you want to continue your Crime Spree?$NL;This will allow you to continue your Crime Spree from $level;$BTN_SPREE_TICKET; to gain Crime Spree Ranks and accumulate greater rewards.$NL;$NL;This will cost you $cost; Continental Coins."	
	})
end)